#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDI_ICON1                               100
#define IDI_ICON2                               101
#define DLG_MAIN                                102
#define DLG_ANALYSIS                            103
#define DLG_ENCDEC                              104
#define DLG_ABOUT                               105
#define DLG_KEYCREATE                           106
#define DLG_CERTTOOL                            107
#define DLG_INLINEHELPER                        108
#define DLG_EVLOG                               109
#define DLG_VERSION                             110
#define DLG_HELP                                111
#define DLG_MISC                                112
#define DLG_NANO                                113
#define IDC_BTN_GENERATE                        1000
#define IDC_BTN_OK                              1000
#define IDC_CHK_LOGFILE                         1000
#define IDC_CHK_LVL10_DECODE                    1000
#define IDC_CHK_OTHERALLOWONE                   1000
#define IDC_LIST                                1000
#define IDC_BTN_DUMP                            1001
#define IDC_CHK_OTHERDISABLEMONITOR             1001
#define IDC_EDT_CURRENTSYM                      1001
#define IDC_EDT_DECODED                         1001
#define IDC_LIST_CERT                           1001
#define IDC_BTN_ABOUT                           1002
#define IDC_BTN_GETCURSYM                       1002
#define IDC_EDT_ENCODED                         1002
#define IDC_EDT_PVT                             1002
#define IDC_PROGRESS_BRUTE                      1002
#define IDC_RADIO_MINIMAL                       1002
#define IDC_STC_TITLE                           1002
#define IDC_BTN_CLEAR                           1003
#define IDC_BTN_DECODE                          1003
#define IDC_CHK_MODKEY                          1003
#define IDC_CHK_OTHERESELLERATE                 1003
#define IDC_EDT_HELPTEXT                        1003
#define IDC_LIST_SECTIONS                       1003
#define IDC_BTN_ENCODE                          1004
#define IDC_BTN_FINDCHECKSUM                    1004
#define IDC_CHK_BRUTESHUTDOWN                   1004
#define IDC_EDT_Y                               1004
#define IDC_RADIO_SPLASHBITMAP                  1004
#define IDC_BTN_DECRYPT                         1005
#define IDC_CHK_BABOON                          1005
#define IDC_EDT_FILE                            1005
#define IDC_RADIO_SPLASHDEFAULT                 1005
#define IDC_BTN_ENCRYPT                         1006
#define IDC_CHK_WATERMARK                       1006
#define IDC_EDT_SERIAL1                         1006
#define IDC_RADIO_COPYMEM2                      1006
#define IDC_BTN_BRUTESETTINGS                   1007
#define IDC_EDT_DATEYMD1                        1007
#define IDC_EDT_ENCRYPTED                       1007
#define IDC_RADIO_DEBUGBLOCKER                  1007
#define IDC_STC_YPUB                            1007
#define IDC_CHK_BRUTESYMVERIFY                  1008
#define IDC_CHK_FOUNDCHECKSUM                   1008
#define IDC_EDT_DECRYPTED                       1008
#define IDC_RADIO_STANDARD                      1008
#define IDC_BTN_GETSECTIONS                     1009
#define IDC_EDT_DATEYMD                         1009
#define IDC_RADIO_SPLASHNONE                    1009
#define IDC_TAB1                                1009
#define IDC_BTN_DELETESECTIONS                  1010
#define IDC_CHK_BRUTENOSYMMETRIC                1010
#define IDC_CHK_LVL10_ENCODE                    1010
#define IDC_CHK_OTHERDIGITALRIVER               1010
#define IDC_BTN_MAKEDATE                        1011
#define IDC_CHK_BRUTE                           1011
#define IDC_EDT_NAME_DECRYPT                    1011
#define IDC_EDT_VERSIONNUM                      1011
#define IDC_LIST_LICENSES                       1011
#define IDC_CHK_OTHERDONTFALLBACK               1012
#define IDC_EDT_NAME_ENCRYPT                    1012
#define IDC_EDT_PROJECTID                       1012
#define IDC_CHK_DUMPDLL                         1013
#define IDC_CHK_IATELIMINATION                  1013
#define IDC_EDT_DATE1                           1013
#define IDC_EDT_SERIAL                          1013
#define IDC_CHK_CODESPLICING                    1014
#define IDC_EDT_DATE2                           1014
#define IDC_EDT_TEMPLATE                        1014
#define IDC_CHK_NANOMITES                       1015
#define IDC_EDT_DATEYMD2                        1015
#define IDC_EDT_HWID                            1015
#define IDC_BTN_GETDATE1                        1016
#define IDC_CHK_MEMPROTECTION                   1016
#define IDC_EDT_NAME                            1016
#define IDC_CHK_ESELLERATE                      1017
#define IDC_EDT_RAWOPTIONS                      1017
#define IDC_EDT_SALT                            1017
#define IDC_BTN_GETDATE2                        1018
#define IDC_CHK_DIGITALRIVER                    1018
#define IDC_CHK_OTHEREXTERNALENV                1018
#define IDC_COMBO_LEVEL                         1019
#define IDC_EDT_CHK                             1019
#define IDC_EDT_EXTRAOPTIONS                    1019
#define IDC_BTN_ANALYZE                         1020
#define IDC_BTN_START                           1020
#define IDC_CHK_OTHERNOCLOCKBACK                1020
#define IDC_CHK_SALT                            1020
#define IDC_BTN_CALCFROMRAW                     1021
#define IDC_EDT_ADVLOG                          1021
#define IDC_BTN_TODAY                           1022
#define IDC_EDT_OTHER0                          1022
#define IDC_RADIO_BACKUPVARIABLE                1022
#define IDC_BTN_GETPROJECTID                    1023
#define IDC_EDT_OTHER1                          1023
#define IDC_RADIO_BACKUPFIXED                   1023
#define IDC_CHK_OVERLAY                         1024
#define IDC_EDT_OTHER2                          1024
#define IDC_RADIO_BACKUPMAIN                    1024
#define IDC_EDT_FIXCLOCKKEY                     1025
#define IDC_EDT_OTHER3                          1025
#define IDC_RADIO_BACKUPNOKEYS                  1025
#define IDC_BTN_GETSALT                         1026
#define IDC_BTN_PAUSE                           1026
#define IDC_EDT_OTHER4                          1026
#define IDC_CHK_LOG                             1027
#define IDC_EDT_SYM                             1027
#define IDC_CHK_ISVALIDSYM                      1028
#define IDC_CHK_OTHERNOCLOCKFORWARD             1028
#define IDC_EDT_KEYSTRING                       1028
#define IDC_BTN_GETMAGIC                        1029
#define IDC_EDT_DATE                            1029
#define IDC_RADIO_COMPRESSIONMINIMAL            1029
#define IDC_STC_STATUS                          1029
#define IDC_CHK_CHECKALLMD5                     1030
#define IDC_EDT_UNINSTALLCODE                   1030
#define IDC_RADIO_COMPRESSIONBETTER             1030
#define IDC_EDT_KEYSTRING_LENGTH                1031
#define IDC_RADIO_COMPRESSIONBEST               1031
#define IDC_BTN_CALC                            1032
#define IDC_BTN_GETLICENSEDATA                  1032
#define IDC_CHK_OTHERSCREENSAVER                1032
#define IDC_BTN_INLINE                          1033
#define IDC_BTN_VERIFYSYM                       1033
#define IDC_CHK_OTHERDISABLEINFO                1033
#define IDC_EDT_FREESPACE                       1034
#define IDC_CHK_ONTOP                           1035
#define IDC_CHK_OTHERIGNOREINFO                 1035
#define IDC_EDT_MAGIC2                          1035
#define IDC_CHK_OTHERDISABLEREGISTER            1036
#define IDC_EDT_GEVA                            1036
#define IDC_EDT_MAGIC1                          1036
#define IDC_CHK_OTHERDISABLEUNREGISTER          1037
#define IDC_EDT_MD5                             1037
#define IDC_EDT_SEVA                            1037
#define IDC_CHK_OTHERAUTOREVERT                 1038
#define IDC_EDT_WPM                             1038
#define IDC_EDT_CRC4                            1039
#define IDC_PROGRESS_SYMVERIFY                  1039
#define IDC_RADIO_ENHANCEDSOFTICE               1039
#define IDC_BTN_PLUGINS                         1040
#define IDC_EDT_SYMFOUND                        1040
#define IDC_RADIO_NORMALNOSOFTICE               1040
#define IDC_BTN_SYMLIST                         1041
#define IDC_EDT_CRC1                            1041
#define IDC_BTN_CERTBIN                         1042
#define IDC_BTN_COPY                            1042
#define IDC_CHK_ENHANCEDHWID                    1042
#define IDC_BTN_REMOVESELLLICDATA               1043
#define IDC_CHK_STANDARDHWID                    1043
#define IDC_EDT_CRC2                            1043
#define IDC_EDT_CRC3                            1044
#define IDC_EDT_CRC5                            1045
#define IDC_BTN_HELP                            1046
#define IDC_BTN_EXIT                            1047
#define IDC_EDT_CRCBASE                         1048
#define IDC_EDT_COUNTER                         1049
#define IDC_EDT_ODSA                            1050
#define IDC_EDT_VP                              1051
#define IDC_EDT_OEP                             1052
#define IDC_EDT_LLA                             1053
#define IDC_EDT_GPA                             1054
#define IDS_HELPKEYGEN                          40000
#define IDS_HELPANALYZE                         40001
#define IDS_HELPKEYFUNCTIONS                    40002
#define IDS_HELPCERTTOOL                        40003
#define IDS_HELPINLINE                          40004
#define IDS_HELPVERSION                         40005
#define IDS_HELPEVLOG                           40006
#define IDS_HELPMISC                            40007
